modLoader="kotori_scala"
loaderVersion="${loader_version_range}"
license="MIT and CC0; see META-INF/LICENSE and META-INF/licenses"
issueTrackerURL="https://github.com/CaitlynMainer/OpenComputers/issues"

[[mods]]
modId="opencomputers"
entryClass="li.cil.oc.OpenComputers"
version="${mod_version}"
displayName="OpenComputers"
displayURL="https://github.com/CaitlynMainer/OpenComputers"
logoFile="pack.png"
credits="Inspired by a couple of other mods, most notably ComputerCraft."
authors="Sangar, Vexatos, payonel, magik6k, Lord Joda, Github Contributors and modern port by akki697222"
description="This mod adds modular computers and robots that can be programmed in Lua."
enumExtensions="META-INF/enumextensions.json"

[[mixins]]
config="opencomputers.mixins.json"

[[mixins]]
config="opencomputers.core.mixins.json"

[[dependencies.opencomputers]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
